livres = []
livres << "veZPDwAAQBAJ"
livres << "1fa2DwAAQBAJ"
livres << "RQZcAQAACAAJ"
livres << "3jihDwAAQBAJ"
livres << "fju3DwAAQBAJ"
livres << "PwSfDwAAQBAJ"
livres << "Dr2CDwAAQBAJ"
livres << "sgKfDwAAQBAJ"
livres << "AyOyDwAAQBAJ"
livres << "hfFIDwAAQBAJ"
livres << "qCdDwAAQBAJ"
livres << "TvWxDwAAQBAJ"
livres << "-si4DwAAQBAJ"
livres << "rtF-BgAAQBAJ"
livres << "RoOYDwAAQBAJ"
livres << "PgvoAwAAQBAJ"
livres << "UM5kPwAACAAJ"
livres << "vGvYBAAAQBAJ"
livres << "WazjBQAAQBAJ"
livres << "QTCxjwEACAAJ"
livres << "MEWlDwAAQBAJ"
livres << "MSCK1GwuiLUC"
livres << "5jLZBAAAQBAJ"
livres << "cxQQvgAACAAJ"
livres << "QLK7n9_28XkC"
livres << "D5ZLAgAAQBAJ"
livres << "4SxEKmerqPUC"
livres << "ThihCgAAQBAJ"
livres << "Bi-NDwAAQBAJ"
livres << "REC1DwAAQBAJ"
livres << "wA_Rp0rBKvsC"
p livres



